"""diagnoses table

Revision ID: 2977e606c234
Revises: e9bad135ac97
Create Date: 2026-08-28 12:27:09.961159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2977e606c234'
down_revision: Union[str, None] = 'e9bad135ac97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('disposition', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('recommended_strategy', sa.String(length=50), nullable=False),
    sa.Column('recommended_delay_hours', sa.Integer(), nullable=True),
    sa.Column('schema_version', sa.String(length=10), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_case_id'), 'diagnoses', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnoses_case_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    # ### end Alembic commands ###
